//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLIBANHANG_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU_FORM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MENU_FORM()
        {
            this.MENU_FORM1 = new HashSet<MENU_FORM>();
            this.APPLICATIONS = new HashSet<APPLICATIONS>();
            this.GROUP_USER_RELATIONSHIP_USER = new HashSet<GROUP_USER_RELATIONSHIP_USER>();
        }
    
        public decimal ID_MENU_FORM { get; set; }
        public string MENU_FORM_NAME { get; set; }
        public string MENU_FORM_URL { get; set; }
        public string MOTA { get; set; }
        public Nullable<byte> SORT_PARENT { get; set; }
        public Nullable<byte> SORT { get; set; }
        public Nullable<decimal> ID_MENU_FORM_PARENT { get; set; }
        public Nullable<bool> DANH_MUC { get; set; }
        public Nullable<bool> VISIBLE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MENU_FORM> MENU_FORM1 { get; set; }
        public virtual MENU_FORM MENU_FORM2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APPLICATIONS> APPLICATIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GROUP_USER_RELATIONSHIP_USER> GROUP_USER_RELATIONSHIP_USER { get; set; }
    }
}
