//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLIBANHANG_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbHOADON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbHOADON()
        {
            this.tbCHITIETHOADON = new HashSet<tbCHITIETHOADON>();
        }
    
        public int MAHOADON { get; set; }
        public Nullable<decimal> MAKHACHHANG { get; set; }
        public Nullable<System.DateTime> NGAY { get; set; }
        public Nullable<decimal> TONGTIEN { get; set; }
    
        public virtual PARTY PARTY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCHITIETHOADON> tbCHITIETHOADON { get; set; }
        public virtual tbKHANHHANG tbKHANHHANG { get; set; }
    }
}
