//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLYBANHANG
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCHITIETHOADON
    {
        public int MACHITIET { get; set; }
        public Nullable<int> MASANPHAM { get; set; }
        public Nullable<decimal> SOLUONG { get; set; }
        public Nullable<decimal> DONGIA { get; set; }
        public Nullable<int> MAHOADON { get; set; }
    
        public virtual tbHOADON tbHOADON { get; set; }
        public virtual tbSANPHAM tbSANPHAM { get; set; }
    }
}
