//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLYBANHANG
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbSANPHAM()
        {
            this.tbCHITIETHOADON = new HashSet<tbCHITIETHOADON>();
        }
    
        public int MASANPHAM { get; set; }
        public string TENSANPHAM { get; set; }
        public Nullable<decimal> DONGIA { get; set; }
        public Nullable<decimal> SOLUONG { get; set; }
        public string HINHANH { get; set; }
        public string MOTA { get; set; }
        public Nullable<int> MADANHMUC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCHITIETHOADON> tbCHITIETHOADON { get; set; }
        public virtual tbDANHMUC tbDANHMUC { get; set; }
    }
}
