//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLYBANHANG_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class GROUP_USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GROUP_USER()
        {
            this.GROUP_USER_RELATIONSHIP_USER = new HashSet<GROUP_USER_RELATIONSHIP_USER>();
        }
    
        public decimal ID_GROUP { get; set; }
        public string GROUP_NAME { get; set; }
        public string DESCRIPTION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GROUP_USER_RELATIONSHIP_USER> GROUP_USER_RELATIONSHIP_USER { get; set; }
    }
}
