//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLYBANHANG_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class GROUP_USER_RELATIONSHIP_USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GROUP_USER_RELATIONSHIP_USER()
        {
            this.MENU_FORM = new HashSet<MENU_FORM>();
        }
    
        public decimal PARTY_ID { get; set; }
        public decimal ID_GROUP { get; set; }
    
        public virtual GROUP_USER GROUP_USER { get; set; }
        public virtual PARTY PARTY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MENU_FORM> MENU_FORM { get; set; }
    }
}
